# Generated by Django 3.0.dev20190224003410 on 2019-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_store', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=444),
        ),
    ]
