# Generated by Django 3.0.dev20190224003410 on 2019-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190425_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbors',
            name='user',
        ),
        migrations.AlterField(
            model_name='asn',
            name='asn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='neighbors',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
