# Generated by Django 3.0.dev20190224003410 on 2019-04-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190426_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(blank=True, null=True)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Prefix')),
            ],
        ),
    ]
