# Generated by Django 3.0.dev20190224003410 on 2019-05-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_notifications_wrong_asn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
    ]
