# Generated by Django 3.0.dev20190224003410 on 2019-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_notifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
