# Generated by Django 3.0.dev20190224003410 on 2019-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190514_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('telegram', models.CharField(max_length=60, null=True)),
                ('hijacked', models.BooleanField(default=0)),
                ('hijacking', models.BooleanField(default=0)),
                ('transited', models.BooleanField(default=0)),
                ('transiting', models.BooleanField(default=0)),
            ],
        ),
    ]
