# Generated by Django 3.0.dev20190224003410 on 2019-05-14 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_notificationrules_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationRules',
            new_name='NotificationRule',
        ),
    ]
