# Generated by Django 3.0.dev20190224003410 on 2019-06-17 08:32

from django.db import migrations
import web.apps.main_app.models.prefix
import web.apps.main_app.validation.ip_validation


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190514_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='broadcast',
            field=web.apps.main_app.models.prefix.IPField(max_length=60, null=True, validators=[web.apps.main_app.validation.ip_validation.validate_ipv46_address]),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='network',
            field=web.apps.main_app.models.prefix.IPField(max_length=60, null=True, validators=[web.apps.main_app.validation.ip_validation.validate_ipv46_address]),
        ),
    ]
