# Generated by Django 3.0.dev20190224003410 on 2019-06-21 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_auto_20190617_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='wrong_asn',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='wrong_prefix',
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='asn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='prefix',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
