# Generated by Django 3.0.dev20190224003410 on 2019-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20190621_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
