# Generated by Django 3.0.dev20190224003410 on 2019-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20190713_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(default='test', max_length=33),
        ),
    ]
