# Generated by Django 3.0.dev20190224003410 on 2019-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20190713_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
