# Generated by Django 3.0.dev20190224003410 on 2019-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_notifications_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status2',
        ),
        migrations.AddField(
            model_name='notifications',
            name='status3',
            field=models.BooleanField(default=0),
        ),
    ]
