# Generated by Django 3.0.dev20190224003410 on 2019-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20190713_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status4',
            field=models.BooleanField(default=0),
        ),
    ]
