# Generated by Django 3.0.dev20190224003410 on 2019-07-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_notifications_status4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='status4',
        ),
    ]
