# Generated by Django 3.0.dev20190224003410 on 2019-07-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20190714_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
