# Generated by Django 3.0.dev20190224003410 on 2019-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_notifications_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status3',
            field=models.BooleanField(default=False),
        ),
    ]
