# Generated by Django 3.0.dev20190224003410 on 2019-07-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_notifications_status3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='status3',
        ),
    ]
