# Generated by Django 3.0.dev20190224003410 on 2019-07-14 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0030_auto_20190714_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='asn',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='asn',
            unique_together={('asn', 'user')},
        ),
    ]
