# Generated by Django 3.0.dev20190224003410 on 2019-07-15 13:28

from django.db import migrations
import web.apps.main_app.models.dump


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20190714_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='prefix',
            field=web.apps.main_app.models.dump.IPField(max_length=60, null=True),
        ),
    ]
