# Generated by Django 3.0.dev20190224003410 on 2019-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_dump_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump',
            name='path',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='prefix',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='path',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
