# Generated by Django 3.0.dev20190224003410 on 2019-09-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20190715_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbors',
            name='left',
        ),
        migrations.RemoveField(
            model_name='neighbors',
            name='right',
        ),
        migrations.AddField(
            model_name='neighbors',
            name='neighbor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neighbors',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='origins',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='main_app.Prefix'),
        ),
    ]
